rplidar_config:
  serial_port: "/dev/rplidar"
  serial_baudrate: 115200
  frame_id: "base_scan"
  inverted: false
  angle_compensate: true
  scan_mode: "Standard"
  max_distance: 10.0

arduino_config:
  serial_port: "/dev/arduino"
  serial_baudrate: 57600
  frame_id: "base_link" # for imu

